branch-defaults:
  master:
    environment: Centra2-env
environment-defaults:
  Centra2-env:
    branch: null
    repository: null
global:
  application_name: centra2
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
